dashboard:
  enabled: true
  service:
    port: 4000
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - host: cypress-dashboard.e2e.local
        path: /
    tls: []
    annotations:
      kubernetes.io/ingress.class: nginx
api:
  env:
    MONGODB_URI: "mongodb://cypress-mongodb-0.cypress-mongodb-headless.default.svc.cluster.local:27017,cypress-mongodb-1.cypress-mongodb-headless.default.svc.cluster.local:27017/?replicaSet=rs0"
mongodb:
  internal_db:
    enabled: true
  persistence:
    enabled: true
    size: 10Gi
    storageClass: standard
    accessModes:
      - ReadWriteOnce
minio:
  enabled: true
  persistence:
    enabled: true
    size: 10Gi
    storageClass: standard
director:
  environmentVariables:
    executionDriver: "../execution/mongo/driver"
