apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cypress
  namespace: default
spec:
  project: default
  source:
    repoURL: https://sorry-cypress.dev/helm-charts/  # Official Helm chart
    targetRevision: 1.20.0
    chart: sorry-cypress
    helm:
      valueFiles:
        - ../../values/values.yaml  # Path to your custom values
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
