apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cypress-dashboard
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fernale/cypress-nginx-chart.git
    targetRevision: HEAD
    path: k8s
    kustomize:
      version: v5.0.0  # TODO
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

