apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cypress-e2e
  namespace: argocd
  labels:
    app.kubernetes.io/instance: cypress-e2e
spec:
  project: default
  source:
    repoURL: https://sorry-cypress.github.io/charts/
    chart: sorry-cypress
    targetRevision: 1.20.0
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
      - RespectIgnoreDifferences=true
    automated:
      prune: true
      selfHeal: true
