apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cypress
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://sorry-cypress.dev/helm-charts/
    chart: sorry-cypress
    targetRevision: 1.20.0
    helm:
      valueFiles:
        - ../../values/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
