apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cypress-cicd
  namespace: argocd
spec:
  project: default
  source:
    chart: sorry-cypress
    repoURL: https://sorry-cypress.github.io/charts
    targetRevision: 1.20.0
    helm:
      values: |
        mongodb:
          mongoConnectionString: "mongodb://cypress-cicd-mongodb-0.cypress-cicd-mongodb-headless.default.svc.cluster.local:27017,cypress-cicd-mongodb-1.cypress-cicd-mongodb-headless.default.svc.cluster.local:27017/sorry-cypress?replicaSet=rs0"
        director:
          url: http://sorry-cypress-director.default.svc.cluster.local
          
        dashboard:
          environmentVariables:
            CYPRESS_DIRECTOR_URL: http://sorry-cypress-director.default.svc.cluster.local
          ingress:
            enabled: true
            hosts:
              - host: sorry-cypress.localhost
                paths:
                  - path: /
                    pathType: Prefix
                    
        api:
          ingress:
            enabled: true
            hosts:
              - host: sorry-cypress-api.localhost
                paths:
                  - path: /
                    pathType: Prefix
                    
        director:
          ingress:
            enabled: true
            hosts:
              - host: sorry-cypress-director.localhost
                paths:
                  - path: /
                    pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
