{{- if .Values.cypress.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cypress-nginx-chart.fullname" . }}-cypress-tests
  labels:
    {{- include "cypress-nginx-chart.labels" . | nindent 4 }}
data:
  "cypress.json": |
    {
      "baseUrl": "{{ .Values.cypress.testConfig.baseUrl }}",
      "reporter": "{{ .Values.cypress.testConfig.reporter }}",
      "video": {{ .Values.cypress.testConfig.video }},
      "screenshotsFolder": "/cypress/cypress/screenshots",
      "videosFolder": "/cypress/cypress/videos",
      "reporterOptions": {
        "reportDir": "/cypress/cypress/reports"
      }
    }
  "integration/dashboard.spec.js": |
    describe('Dashboard Test', function() {
      it('Successfully loads dashboard', function() {
        cy.visit('/')
        cy.contains('Cypress Test Dashboard')
      })
      
      it('Shows test report links', function() {
        cy.visit('/')
        cy.contains('View Test Reports')
        cy.contains('View Test Videos')
        cy.contains('View Screenshots')
      })
    })
{{- end }}

