apiVersion: v1
kind: Service
metadata:
  name: {{ include "cypress-nginx-chart.fullname" . }}
  labels:
    {{- include "cypress-nginx-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: http
      {{- if eq .Values.nginx.service.type "NodePort" }}
      nodePort: {{ .Values.nginx.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "cypress-nginx-chart.selectorLabels" . | nindent 4 }}

