apiVersion: batch/v1
kind: CronJob
metadata:
  name: cypress-results-cleanup
spec:
  schedule: "0 2 * * *"  # Every day at 2am
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cleanup
            image: alpine:3.18
            command: ["/bin/sh", "-c"]
            args:
              - find /results -type f -mtime +15 -delete
            volumeMounts:
              - name: results
                mountPath: /results
          restartPolicy: OnFailure
          volumes:
            - name: results
              persistentVolumeClaim:
                claimName: cypress-results

