apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cypress-results
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard

